# =================================
# environments/production/group_vars/all.yml
# =================================
---
#slack_channel: "splunk-enterprise-ansible"
#slack_token: "T08HVQJMLN8/B094J0Q4C4A/XWe29Bh70TAptpfFfcIqZDkg"
ansible_user: ansible
ansible_ssh_private_key_file: /home/jamel/.ssh/ansible_key
ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
ansible_become: true
ansible_become_method: sudo
ansible_become_pass: ansible123
ansible_environment:
  PATH: "/usr/local/bin:/usr/bin:/bin:{{ ansible_env.PATH | default('') }}"
  
splunk_package_path: /tmp
git_local_clone_path: /tmp/
splunk_download_local: true
splunk_home: "/opt/splunk"
splunkbase_apps_dir: "/home/jamel/splunkbase-apps"

# Splunkbase authentication (replace with your credentials)
splunkbase_username: "user@splunk.com"
splunkbase_password: "yourpassword"
splunkbase_auth_url: "https://splunkbase.splunk.com/api/account:login/"

# MinIO configuration for Splunkbase app caching
minio_enabled: true
minio_endpoint: "http://your-minio-server:9000"
minio_access_key: "your-access-key"
minio_secret_key: "your-secret-key"
minio_bucket: "splunkbase-apps"
minio_secure: false  # Set to true for HTTPS

git_server: "git@github.com:gusdebbaja"
git_project: "splunk-apps"
git_key: "/home/jamel/.ssh/git_key"  # Absolute path
monorepo_checkout_dir: "/tmp/splunk-apps-checkout"
git_version: main
git_apps:
  - name: ssl_enablement
    git_server: "git@github.com:gusdebbaja"
    git_project: "splunk-apps"
    app_relative_path: "/common/ssl_enablement/"
    splunk_app_deploy_path: "etc/apps"
    
  - name: indexer_apps  
    git_server: "git@github.com:gusdebbaja"
    git_project: "splunk-apps"
    app_relative_path: "/indexers/"
    splunk_app_deploy_path: "etc/apps"

# License Master URI (all peers will connect to this)
splunk_uri_lm: https://splunk-mgmt:8089

# Deployment Server URI (for forwarders)
splunk_uri_ds: https://splunk-mgmt:8089

# System Configuration
update_system_packages: true
splunk_package_version: 9.3.4
build_id: 30e72d3fb5f7
#splunk_package_version: 9.4.0
#build_id: 6b4ebe426ca6

# Admin Credentials
splunk_admin_username: admin
splunk_admin_password: admin123

# Basic Splunk Configuration
splunk_install_path: /opt
splunk_nix_user: splunk
splunk_nix_group: splunk

# License Configuration
splunk_license_group: Enterprise 
splunk_license_file: 
  - "Splunk.license"

splunk_uri_cm: https://splunk-mgmt:8089

# IDXC Vars
splunk_idxc_key: mypass4symmkey
splunk_idxc_rf: 2
splunk_idxc_sf: 2
splunk_idxc_rep_port: 9887
splunk_idxc_label: myidxc

# SHC Vars
splunk_shc_key: mypass4symmkey
splunk_shc_label: augment_shc
splunk_shc_rf: 2
splunk_shc_target_group: augment_shc
splunk_shc_deployer: "{{ groups['shdeployer'] | first }}"  # If you manage multiple SHCs, configure the var value in group_vars
splunk_shc_uri_list: "{% for h in groups[splunk_shc_target_group] %}https://{{ hostvars[h].splunk_mgmt_uri }}:{{ splunkd_port }}{% if not loop.last %},{% endif %}{% endfor %}"  # If you manage multiple SHCs, configure the var value in group_vars

# Network Configuration
splunk_mgmt_uri: "{{ ansible_fqdn | default(ansible_default_ipv4.address) }}"
splunkd_port: 8089

# Service Configuration
splunk_use_systemd: true
splunk_create_polkit: 1

# Security
splunk_general_key: "SuperSecretPassKey"
splunk_ds_key: "dpskey"
splunk_configure_secret: false

# Firewall Configuration
configure_firewall: true
#splunk_firewall_ports:
#  - "{{ splunkweb_port }}"
#  - "{{ splunkapi_port }}"

# System Optimization
install_utilities: false
use_tuned_thp: true

# Maintenance Scripts
add_crashlog_script: true
add_diag_script: true
add_pstack_script: true
configure_dmesg: false