git_apps:
  - name: splunk-apps
    app_relative_path: /common/ssl_enablement/
    splunk_app_deploy_path: etc/apps
    git_server: "git@github.com:gusdebbaja"  # Add this
    git_project: "splunk-apps"               # Add this
  - name: splunk-apps
    app_relative_path: /deployment_server/universal_forwarders/deployment_client/  # For internal log forwarding
    splunk_app_deploy_path: etc/apps
    git_server: "git@github.com:gusdebbaja"  # Add this
    git_project: "splunk-apps"               # Add this
