---
# SSH Key Distribution Playbook (using built-in modules only)
- name: Distribute SSH Keys to All Hosts
  hosts: all
  gather_facts: false
  vars:
    ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
  tasks:
    - name: Test SSH connectivity with password authentication
      ping:
      delegate_to: "{{ inventory_hostname }}"
      
    - name: Ensure .ssh directory exists
      file:
        path: "~/.ssh"
        state: directory
        mode: '0700'
      become: false
      
    - name: Read the SSH public key content
      set_fact:
        ssh_pub_key: "{{ lookup('file', lookup('env', 'HOME') + '/.ssh/ansible_key.pub') }}"
      delegate_to: localhost
      run_once: true
      
    - name: Create authorized_keys file if it doesn't exist
      file:
        path: "~/.ssh/authorized_keys"
        state: touch
        mode: '0600'
      become: false
      
    - name: Check if key already exists in authorized_keys
      lineinfile:
        path: "~/.ssh/authorized_keys"
        line: "{{ ssh_pub_key }}"
        state: present
      become: false
      check_mode: yes
      register: key_exists
      
    - name: Add SSH public key to authorized_keys
      lineinfile:
        path: "~/.ssh/authorized_keys"
        line: "{{ ssh_pub_key }}"
        state: present
        create: yes
        mode: '0600'
      become: false
      when: key_exists is changed
      
    - name: Test SSH key authentication
      ping:
      vars:
        ansible_ssh_common_args: '-o PasswordAuthentication=no -o StrictHostKeyChecking=no'