---
# ===============================================================================
# Fix Search Head App Permissions
# Run this after shcluster-bundle deployment to fix permission issues
# ===============================================================================

- name: Fix Search Head App Permissions After Bundle Deployment
  hosts: search
  become: true
  gather_facts: false
  vars:
    splunk_home: "/opt/splunk"
    splunk_nix_user: "splunk"
    splunk_nix_group: "splunk"
    
  tasks:
    - name: Find all apps in search head apps directory
      find:
        paths: "{{ splunk_home }}/etc/apps"
        file_type: directory
        recurse: no
      register: search_head_apps

    - name: Fix permissions for each search head app
      include_tasks: ../custom_roles/splunk_apps/tasks/fix_splunk_permissions_unified.yml
      vars:
        target_app_path: "{{ app_dir.path }}"
      loop: "{{ search_head_apps.files }}"
      loop_control:
        loop_var: app_dir
      when: search_head_apps.files | length > 0

    - name: Show summary
      debug:
        msg: "✅ Fixed permissions for {{ search_head_apps.files | length }} apps on {{ inventory_hostname }}"