---
# Playbook to perform either a splunk installation or upgrade with cluster configuration
# Phase 1: Install/Upgrade Splunk
- hosts: all
  roles:
    - ../roles/ansible-role-for-splunk
  serial: 50
  vars:
    deployment_task: check_splunk.yml

# Phase 2: Configure Search Head Cluster
- hosts: shdeployer
  roles:
    - ../roles/ansible-role-for-splunk
  vars:
    deployment_task: configure_shc_deployer.yml

- hosts: search
  roles:
    - ../roles/ansible-role-for-splunk
  vars:
    deployment_task: configure_shc_members.yml

- hosts: search[0]
  roles:
    - ../roles/ansible-role-for-splunk
  vars:
    deployment_task: configure_shc_captain.yml

# Phase 3: Configure Indexer Cluster
- hosts: clustermanager
  roles:
    - ../roles/ansible-role-for-splunk
  vars:
    deployment_task: configure_idxc_manager.yml

- hosts: indexer
  roles:
    - ../roles/ansible-role-for-splunk
  vars:
    deployment_task: configure_idxc_member.yml

# Phase 3.5: Connect Search Heads to Indexer Cluster
- hosts: search
  roles:
    - ../roles/ansible-role-for-splunk
  vars:
    deployment_task: configure_idxc_sh.yml

# Phase 4: Configure Deployment Clients  
- hosts: search:heavyforwarder
  roles:
    - ../roles/ansible-role-for-splunk
  vars:
    deployment_task: configure_deploymentclient.yml
    splunk_uri_ds: https://splunk-mgmt:8089