---
# Splunk Software Installation/Upgrade Playbook with Indexer Clustering Configuration
# Purpose: Install or upgrade Splunk software and configure indexer clustering
# Usage: ansible-playbook -i inventory.yml splunk_install.yml --ask-vault-pass

# Phase 1: Deploy License Master first
- name: Deploy License Master
  hosts: licensemaster
  pre_tasks:
    - name: Ensure /etc/logrotate.d/syslog exists
      file:
        path: /etc/logrotate.d/syslog
        state: touch
        mode: '0644'
      when: ansible_os_family == 'RedHat'

  become: true
  gather_facts: true
  vars:
    deployment_task: check_splunk.yml
  roles:
    - ansible-role-for-splunk
  tags: [licensemaster]

# Phase 2: Deploy Deployment Server and Search Head Deployer
- name: Deploy Deployment Server  
  hosts: deploymentserver
  become: true
  gather_facts: true
  vars:
    deployment_task: check_splunk.yml
  roles:
    - ansible-role-for-splunk
  tags: [deploymentserver]

- name: Deploy Search Head Deployer
  hosts: shdeployer
  become: true
  gather_facts: true
  vars:
    deployment_task: check_splunk.yml
  roles:
    - ansible-role-for-splunk
  tags: [shdeployer]

# Phase 3: Deploy Cluster Manager (if using indexer clustering)
- name: Deploy Cluster Manager
  hosts: clustermanager
  pre_tasks:
    - name: Ensure /etc/logrotate.d/syslog exists
      file:
        path: /etc/logrotate.d/syslog
        state: touch
        mode: '0644'
      when: ansible_os_family == 'RedHat'

  become: true
  gather_facts: true
  vars:
    deployment_task: check_splunk.yml
  roles:
    - ansible-role-for-splunk
  tags: [clustermanager]

# Phase 4: Deploy Indexers
- name: Deploy Indexers
  hosts: indexer  
  pre_tasks:
    - name: Ensure /etc/logrotate.d/syslog exists
      file:
        path: /etc/logrotate.d/syslog
        state: touch
        mode: '0644'
      when: ansible_os_family == 'RedHat'

  become: true
  gather_facts: true
  serial: 1  # Deploy one at a time for safety
  vars:
    deployment_task: check_splunk.yml
  roles:
    - ansible-role-for-splunk
  tags: [indexer]

# Phase 5: Deploy Search Heads and Search Head Cluster Members
- name: Deploy Search Heads
  hosts: search
  pre_tasks:
    - name: Ensure /etc/logrotate.d/syslog exists
      file:
        path: /etc/logrotate.d/syslog
        state: touch
        mode: '0644'
      when: ansible_os_family == 'RedHat'

  become: true
  gather_facts: true
  vars:
    deployment_task: check_splunk.yml
  roles:
    - ansible-role-for-splunk
  tags: [search]

- name: Deploy Search Head Cluster Members
  hosts: shc
  pre_tasks:
    - name: Ensure /etc/logrotate.d/syslog exists
      file:
        path: /etc/logrotate.d/syslog
        state: touch
        mode: '0644'
      when: ansible_os_family == 'RedHat'

  become: true
  gather_facts: true
  vars:
    deployment_task: check_splunk.yml
  roles:
    - ansible-role-for-splunk
  tags: [shc]

# Phase 6: Deploy Heavy Forwarders
- name: Deploy Heavy Forwarders
  hosts: heavyforwarder
  pre_tasks:
    - name: Ensure /etc/logrotate.d/syslog exists
      file:
        path: /etc/logrotate.d/syslog
        state: touch
        mode: '0644'
      when: ansible_os_family == 'RedHat'

  become: true
  gather_facts: true
  vars:
    deployment_task: check_splunk.yml
  roles:
    - ansible-role-for-splunk
  tags: [heavyforwarder]

# Phase 6.5: Configure Heavy Forwarder Deployment Clients
- name: Configure Heavy Forwarder Deployment Clients
  hosts: heavyforwarder
  become: true
  gather_facts: true
  vars:
    deployment_task: configure_deploymentclient.yml
  roles:
    - ansible-role-for-splunk
  tags: [heavyforwarder_deploymentclient]

# Phase 7: Deploy Universal Forwarders
- name: Deploy Universal Forwarders
  hosts: uf
  pre_tasks:
    - name: Ensure /etc/logrotate.d/syslog exists
      file:
        path: /etc/logrotate.d/syslog
        state: touch
        mode: '0644'
      when: ansible_os_family == 'RedHat'

  become: true
  gather_facts: true
  serial: 10  # Deploy 10 at a time
  vars:
    deployment_task: check_splunk.yml
  roles:
    - ansible-role-for-splunk
  tags: [uf]

# Phase 8: Configure Cluster Manager (INDEXER CLUSTERING)
- name: Configure Cluster Manager for Indexer Clustering
  hosts: clustermanager
  become: true
  gather_facts: true
  vars:
    deployment_task: configure_idxc_manager.yml
  roles:
    - ansible-role-for-splunk
  tags: [clustering, idxc_manager]

# Phase 9: Configure Indexer Cluster Members (INDEXER CLUSTERING)
- name: Configure Indexer Cluster Members
  hosts: indexer
  become: true
  gather_facts: true
  serial: 1  # Configure one at a time for safety
  vars:
    deployment_task: configure_idxc_member.yml
  roles:
    - ansible-role-for-splunk
  tags: [clustering, idxc_member]

# Phase 10: Configure Search Head Deployer (SEARCH HEAD CLUSTERING)
- name: Configure Search Head Deployer
  hosts: shdeployer
  become: true
  gather_facts: true
  vars:
    deployment_task: configure_shc_deployer.yml
  roles:
    - ansible-role-for-splunk
  tags: [clustering, shc_deployer]

# Phase 11: Configure Search Head Cluster Members (SEARCH HEAD CLUSTERING)
- name: Configure Search Head Cluster Members
  hosts: search
  become: true
  gather_facts: true
  vars:
    deployment_task: configure_shc_members.yml
  roles:
    - ansible-role-for-splunk
  tags: [clustering, ]

# Phase 12: Configure Search Head Cluster Captain (SEARCH HEAD CLUSTERING)
- name: Configure Search Head Cluster Captain
  hosts: search
  become: true
  gather_facts: true
  vars:
    deployment_task: configure_shc_captain.yml
  roles:
    - ansible-role-for-splunk
  tags: [clustering, shc_captain]

# Phase 13: Configure Search Heads to Join Indexer Cluster (INDEXER CLUSTERING)
# Note: This applies to both standalone search heads and search head cluster members
- name: Configure Search Heads to Join Indexer Cluster
  hosts: search:shc
  become: true
  gather_facts: true
  vars:
    deployment_task: configure_idxc_sh.yml
  roles:
    - ansible-role-for-splunk
  tags: [clustering, idxc_sh]

# Phase 14: Configure Deployment Server (server classes, etc.)
- name: Configure Deployment Server
  hosts: deploymentserver
  become: true
  gather_facts: true
  vars:
    deployment_task: configure_serverclass.yml
  roles:
    - ansible-role-for-splunk
  tags: [deploymentserver_config]

# Phase 15: Configure DMC (Distributed Monitoring Console) if present
- name: Configure DMC
  hosts: dmc
  become: true
  gather_facts: true
  vars:
    deployment_task: configure_dmc.yml
  roles:
    - ansible-role-for-splunk
  tags: [dmc]
