# playbooks/splunk_verify.yml  
# Verification-only playbook for health checks
- name: Verify Splunk Environment Health
  hosts: all:!localhost
  become: true
  gather_facts: true
  
  tasks:
    - name: Debug AWX environment
      debug:
        msg:
          - "Working directory: {{ ansible_env.PWD | default('UNDEFINED') }}"
          - "Splunk home from vars: {{ splunk_home | default('UNDEFINED') }}"
          - "Current user: {{ ansible_user_id | default('UNDEFINED') }}"
          - "Inventory file: {{ inventory_file | default('UNDEFINED') }}"
          - "Target IP: {{ ansible_host | default('NO_ANSIBLE_HOST') }}"
          - "Actual hostname: {{ ansible_hostname | default('UNDEFINED') }}"
          - "Detected IP: {{ ansible_default_ipv4.address | default('UNDEFINED') }}"
      tags: debug

    - name: Check Splunk process status
      command: "{{ splunk_home }}/bin/splunk status"
      register: splunk_status
      become_user: "{{ splunk_nix_user | default('splunk') }}"
      failed_when: false
      
    - name: Check disk space
      command: df -h {{ splunk_home }}
      register: disk_usage
      failed_when: false

    - name: Count deployed apps
      find:
        paths: "{{ splunk_home }}/etc/apps"
        file_type: directory
      register: app_count
      failed_when: false

    - name: Test web interface (search heads only)
      uri:
        url: "https://{{ ansible_default_ipv4.address }}:8000"
        method: GET
        validate_certs: false
        status_code: [200, 401, 302]
      register: web_test
      when: "'search' in group_names"
      failed_when: false

    - name: Debug variables (for troubleshooting)
      debug:
        msg:
          - "splunk_home: {{ splunk_home | default('UNDEFINED') }}"
          - "splunk_status.rc: {{ splunk_status.rc | default('UNDEFINED') }}"
          - "disk_usage.rc: {{ disk_usage.rc | default('UNDEFINED') }}"
      when: ansible_verbosity >= 2

    - name: Display health summary
      debug:
        msg:
          - "=== {{ inventory_hostname }} HEALTH CHECK ==="
          - "Groups: {{ group_names }}"
          - "Splunk Status: {{ splunk_status.stdout.split('\\n')[0] if splunk_status.stdout is defined and splunk_status.stdout != '' else ('FAILED: ' + (splunk_status.stderr | default('No error info'))) }}"
          - "Disk Usage: {{ disk_usage.stdout.split('\\n')[0] if disk_usage.stdout is defined and disk_usage.stdout != '' else ('FAILED: ' + (disk_usage.stderr | default('No error info'))) }}"
          - "Apps Count: {{ app_count.files | length if app_count is defined and app_count.files is defined else 'N/A' }}"
          - "Web Interface: {{ 'OK' if web_test.status is defined and web_test.status in [200, 401, 302] else 'N/A' }}"