---
- name: Set default paths if not defined
  set_fact:
    app_templates_path: "{{ app_templates_path | default('/tmp/splunk-apps-checkout/app-templates') }}"
    generated_apps_path: "{{ generated_apps_path | default('/tmp/generated-splunk-apps') }}"
    cleanup_generated_apps: "{{ cleanup_generated_apps | default(true) }}"

- name: Debug template app configuration
  debug:
    msg:
      - "=== TEMPLATE APP GENERATION FOR {{ inventory_hostname }} ==="
      - "Host groups: {{ group_names }}"
      - "Environment: {{ environment | default('not_set') }}"
      - "Tenant: {{ tenant | default('not_set') }}"
      - "Team: {{ team_name | default('not_set') }}"
      - "Organization: {{ organization_name | default('not_set') }}"
      - "Template path: {{ app_templates_path }}"
      - "Generated path: {{ generated_apps_path }}"
      - "Generate for all hosts: {{ generate_for_all_hosts | default(false) }}"
      - "Target host groups: {{ target_host_groups | default('not_set') }}"

# Different behavior based on execution mode
- name: Generate templates for all hosts (localhost mode)
  include_tasks: generate_all_host_templates.yml
  when: 
    - inventory_hostname == 'localhost'
    - generate_for_all_hosts | default(false)

- name: Generate and deploy templates for current host
  include_tasks: generate_current_host_templates.yml
  when: 
    - inventory_hostname != 'localhost'
    - "'full' in group_names or 'uf' in group_names"

- name: Set template apps processed count
  set_fact:
    template_apps_processed: "{{ template_apps_deployed | default([]) | length }}"