---
# ===============================================================================
# Process search head-specific resources from enhanced template format
# ===============================================================================

- name: Debug search head resources
  debug:
    msg:
      - "Processing search head resources for {{ template_name }}"
      - "Search head config: {{ template_metadata.search_heads }}"
  when: debug_enabled | default(false)

- name: Process each search head app
  include_tasks: process_single_search_head_app.yml
  loop: "{{ template_metadata.search_heads.app | default([]) }}"
  loop_control:
    loop_var: sh_app_config
  when: template_metadata.search_heads.app is defined

- name: Generate default search head app if no specific apps defined
  block:
    - name: Prepare search head-specific variables
      set_fact:
        sh_template_vars: "{{ base_merged_vars | combine({
          'role_type': 'search_head'
        }) }}"

    - name: Combine with template-specific vars
      set_fact:
        sh_template_vars: "{{ sh_template_vars | combine(base_template_vars) }}"

    - name: Add default template vars (lowest priority)
      set_fact:
        sh_template_vars: "{{ sh_template_vars | combine(default_template_vars | default({})) }}"

    - name: Add environment-specific vars
      set_fact:
        sh_template_vars: "{{ sh_template_vars | combine(default_environment_vars[environment] | default({})) }}"

    - name: Add group vars (template_vars from group_vars)
      set_fact:
        sh_template_vars: "{{ sh_template_vars | combine(template_vars | default({})) }}"

    - name: Add host vars (additional_template_vars from host_vars)
      set_fact:
        sh_template_vars: "{{ sh_template_vars | combine(additional_template_vars | default({})) }}"

    - name: Calculate search head app name
      set_fact:
        sh_app_name: "{{ (base_merged_vars.tenant + '_' + base_merged_vars.app_name + '_search') | lower }}"

    - name: Generate search head app
      include_tasks: generate_single_app.yml
      vars:
        app_name: "{{ sh_app_name }}"
        app_template_vars: "{{ sh_template_vars }}"
        app_metadata: "{{ template_metadata }}"
        source_template_dir: "{{ template_dir.path }}"

  when: template_metadata.search_heads.app is not defined