# ===============================================================================
# custom_roles/splunk_app_templates/tasks/process_template_for_host.yml
# ===============================================================================
---
# Process individual template for specific host - Enhanced with backward compatibility

# Use the new enhanced template processor
- include_tasks: process_enhanced_template.yml